### PR TITLE
Finished most of Aaron's recommendations/questions/remarks

### PR DESCRIPTION
**Pull request by DavidHSell**

### CODE REVIEW

**Comment by aaronsaray** [comment]
Please do not merge in pull requests yourself!

**Comment by aaronsaray** [comment]
Please issue a revert on this pull request.  Since you did a pull request - that's where it should stop.  Now that you've merged it, you've basically pushed this to production without us having a chance to review it.

**Comment by DavidHSell** [comment]
Sorry, but that was the intent.  What should I do?

**Comment by aaronsaray** [comment]
You have to go in to the web interface. There should be some sort of revert
button. That will create a new pull request of the unmerged stuff. Then you
merge in that pull request.

I'd help but I'm not near a computer. I just happened to see the emails
come through

**Comment by DavidHSell** [comment]
We will have to coordinate this between you, me, and Balentine.  I did not want them looking at the old version.  This all happened in a phone conference where they seemed put-off that it was not ready, and were asking highly detailed questions about it.  So next week, we should contact them to let them know we are doing a temporary roll-back so you can see all the diffs.  They are using it heavily today, so I didn't want them seeing the syntax errors that were in there.

**Pull request merged**
